const GET_WEATHER = 'GET_WEATHER'
const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
const GET_WEATHER_ERROR = 'GET_WEATHER_ERROR'

export default {
  GET_WEATHER,
  GET_WEATHER_SUCCESS,
  GET_WEATHER_ERROR,
}
